name: Sync to Gitee
on:
  push:
    branches: ["**"]
    tags: ["**"]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push all branches and tags to Gitee
        env:
          GITEE_USERNAME: ${{ secrets.GITEE_USERNAME }}
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
        run: |
          git remote add gitee "https://${GITEE_USERNAME}:${GITEE_TOKEN}@gitee.com/${GITEE_USERNAME}/${GITHUB_REPOSITORY#*/}.git"
          git push --force --prune gitee 'refs/heads/*:refs/heads/*' 'refs/tags/*:refs/tags/*'